version: "3"
services:
  nginx:
    build:
      context: "."
      dockerfile: "Dockerfile-${PHP_VERSION}"
      args:
        - "SERVER_ROOT=${SERVER_ROOT}"
        - "PHP_VERSION=${PHP_VERSION}"
        - "DISPLAY_PHPERROR=${DISPLAY_PHPERROR}"
        - "MONGODB_VERSION=${MONGODB_VERSION}"
    volumes:
      - "${APP_CODE_PATH_HOST}:${APP_CODE_PATH_NGINX}${APP_CODE_CONTAINER_FLAG}"
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
  mongoclient:
    image: mongoclient/mongoclient:latest
    ports:
      - "3300:3000"
  mongo:
    build: "./mongo"
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - "${DATA_PATH_HOST}/mongo:/data/db"
      - "${DATA_PATH_HOST}/mongo_config:/data/configdb"
      
volumes: {}
